import React, { useEffect, useState } from "react";
import CommonListViewTable from "../../../utils/CommonListViewTable";

const PartyMasterList = ({ onAddNew, onEdit,onBack }) => {
  const [partyData, setPartyData] = useState([]);
  const [loading, setLoading] = useState(false);

  const loadParties = async () => {
    setLoading(true);

    // Dummy Data
   const data = [
  {
    id: 6,
    partyCode: "PTY006",
    partyName: "ABC Traders",
    shortName: "ABC",
    gstPartyName: "ABC Traders Pvt Ltd",
    partyType: "Customer",
    customerType: "Retail",
    agentName: "Rajesh Kumar",
    accountType: "Sundry Debtor",
    businessType: "Trading",
    carrierCode: "CR001",
    supplierType: "Local",
    salesPerson: "Amit",
    customerCoordinator: "Priya",
    accountName: "ABC Traders A/c",
    gstRegistered: true,
    gstNo: "29ABCDE1234F1Z5",
    creditLimit: 500000,
    creditDays: 30,
    panNo: "ABCDE1234F",
    controllingOffice: "Bangalore HO",
    currency: "INR",
    panName: "ABC Traders Pvt Ltd",
    airWayBillCode: "AWB001",
    airlineCode: "AI",
    tanNo: "BLRA12345B",
    businessCategory: "Wholesale",
    country: "India",
    caf: "CAF001",
    compoundingScheme: "No",
    psuGovtOrganization: "No",
    remarks: "Preferred Customer",
    active: true,
    bankName: "HDFC Bank",
    branch: "MG Road",
    bankAddress: "MG Road, Bangalore",
    accountNo: "123456789012",
    accountTypeBank: "Current",
    ifscCode: "HDFC0001234",
    swift: "HDFCINBB",
    contactPerson: "Rahul Sharma",
    mobile: "9876543210",
    contactEmail: "rahul@abctraders.com",
    city: "Bangalore",
    state: "Karnataka",
    stateCode: "KA",
    stateNo: 29,
  },
  {
    id: 5,
    partyCode: "PTY005",
    partyName: "Global Suppliers",
    shortName: "GLOBAL",
    gstPartyName: "Global Suppliers Ltd",
    partyType: "Vendor",
    customerType: "Wholesale",
    agentName: "Vijay",
    accountType: "Sundry Creditor",
    businessType: "Manufacturing",
    carrierCode: "CR002",
    supplierType: "Import",
    salesPerson: "Anil",
    customerCoordinator: "Deepa",
    accountName: "Global Suppliers A/c",
    gstRegistered: true,
    gstNo: "36ABCDE5678K1Z2",
    creditLimit: 750000,
    creditDays: 45,
    panNo: "ABCDE5678K",
    controllingOffice: "Hyderabad HO",
    currency: "INR",
    panName: "Global Suppliers Ltd",
    airWayBillCode: "AWB002",
    airlineCode: "6E",
    tanNo: "HYDA12345C",
    businessCategory: "Industrial",
    country: "India",
    caf: "CAF002",
    compoundingScheme: "No",
    psuGovtOrganization: "No",
    remarks: "Major Vendor",
    active: true,
    bankName: "ICICI Bank",
    branch: "Banjara Hills",
    bankAddress: "Hyderabad",
    accountNo: "987654321000",
    accountTypeBank: "Current",
    ifscCode: "ICIC0002345",
    swift: "ICICINBB",
    contactPerson: "Priya Nair",
    mobile: "9988776655",
    contactEmail: "priya@globalsuppliers.com",
    city: "Hyderabad",
    state: "Telangana",
    stateCode: "TS",
    stateNo: 36,
  },
  {
    id: 4,
    partyCode: "PTY004",
    partyName: "Sunrise Enterprises",
    shortName: "SUNRISE",
    gstPartyName: "Sunrise Enterprises",
    partyType: "Customer",
    customerType: "Corporate",
    agentName: "Mahesh",
    accountType: "Sundry Debtor",
    businessType: "Services",
    carrierCode: "CR003",
    supplierType: "Domestic",
    salesPerson: "Kiran",
    customerCoordinator: "Meena",
    accountName: "Sunrise A/c",
    gstRegistered: true,
    gstNo: "33ABCDE1111H1Z7",
    creditLimit: 300000,
    creditDays: 20,
    panNo: "ABCDE1111H",
    controllingOffice: "Chennai",
    currency: "INR",
    panName: "Sunrise Enterprises",
    airWayBillCode: "AWB003",
    airlineCode: "SG",
    tanNo: "CHNA12345D",
    businessCategory: "IT",
    country: "India",
    caf: "CAF003",
    compoundingScheme: "Yes",
    psuGovtOrganization: "No",
    remarks: "Regular Customer",
    active: false,
    bankName: "SBI",
    branch: "Anna Salai",
    bankAddress: "Chennai",
    accountNo: "456789123456",
    accountTypeBank: "Savings",
    ifscCode: "SBIN0003456",
    swift: "SBININBB",
    contactPerson: "Arjun Kumar",
    mobile: "9123456789",
    contactEmail: "arjun@sunrise.com",
    city: "Chennai",
    state: "Tamil Nadu",
    stateCode: "TN",
    stateNo: 33,
  },
  {
    id: 3,
    partyCode: "PTY003",
    partyName: "Prime Distributors",
    shortName: "PRIME",
    gstPartyName: "Prime Distributors",
    partyType: "Vendor",
    customerType: "Dealer",
    agentName: "Ganesh",
    accountType: "Sundry Creditor",
    businessType: "Distribution",
    carrierCode: "CR004",
    supplierType: "Local",
    salesPerson: "Suresh",
    customerCoordinator: "Nisha",
    accountName: "Prime A/c",
    gstRegistered: true,
    gstNo: "27ABCDE9999L1Z3",
    creditLimit: 450000,
    creditDays: 25,
    panNo: "ABCDE9999L",
    controllingOffice: "Pune",
    currency: "INR",
    panName: "Prime Distributors",
    airWayBillCode: "AWB004",
    airlineCode: "UK",
    tanNo: "PUNA12345E",
    businessCategory: "Wholesale",
    country: "India",
    caf: "CAF004",
    compoundingScheme: "No",
    psuGovtOrganization: "No",
    remarks: "",
    active: true,
    bankName: "Axis Bank",
    branch: "Shivaji Nagar",
    bankAddress: "Pune",
    accountNo: "123123123123",
    accountTypeBank: "Current",
    ifscCode: "UTIB0004567",
    swift: "AXISINBB",
    contactPerson: "Sneha Rao",
    mobile: "9012345678",
    contactEmail: "sneha@prime.com",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "MH",
    stateNo: 27,
  },
  {
    id: 2,
    partyCode: "PTY002",
    partyName: "Tech Solutions",
    shortName: "TECH",
    gstPartyName: "Tech Solutions Pvt Ltd",
    partyType: "Customer",
    customerType: "Corporate",
    agentName: "Rohit",
    accountType: "Sundry Debtor",
    businessType: "Software",
    carrierCode: "CR005",
    supplierType: "Domestic",
    salesPerson: "Akash",
    customerCoordinator: "Divya",
    accountName: "Tech Solutions A/c",
    gstRegistered: true,
    gstNo: "27ABCDE5555P1Z6",
    creditLimit: 1000000,
    creditDays: 60,
    panNo: "ABCDE5555P",
    controllingOffice: "Mumbai",
    currency: "INR",
    panName: "Tech Solutions Pvt Ltd",
    airWayBillCode: "AWB005",
    airlineCode: "AI",
    tanNo: "MUMA12345F",
    businessCategory: "IT",
    country: "India",
    caf: "CAF005",
    compoundingScheme: "No",
    psuGovtOrganization: "No",
    remarks: "VIP Customer",
    active: true,
    bankName: "Kotak Mahindra Bank",
    branch: "Andheri",
    bankAddress: "Mumbai",
    accountNo: "789456123000",
    accountTypeBank: "Current",
    ifscCode: "KKBK0005678",
    swift: "KKBKINBB",
    contactPerson: "John Peter",
    mobile: "9090909090",
    contactEmail: "john@techsolutions.com",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "MH",
    stateNo: 27,
  },
  {
    id: 1,
    partyCode: "PTY001",
    partyName: "Sri Lakshmi Agencies",
    shortName: "SLA",
    gstPartyName: "Sri Lakshmi Agencies",
    partyType: "Vendor",
    customerType: "Distributor",
    agentName: "Ramesh",
    accountType: "Sundry Creditor",
    businessType: "Wholesale",
    carrierCode: "CR006",
    supplierType: "Local",
    salesPerson: "Manoj",
    customerCoordinator: "Lakshmi",
    accountName: "Sri Lakshmi A/c",
    gstRegistered: false,
    gstNo: "",
    creditLimit: 150000,
    creditDays: 15,
    panNo: "ABCDE7777M",
    controllingOffice: "Mysore",
    currency: "INR",
    panName: "Sri Lakshmi Agencies",
    airWayBillCode: "AWB006",
    airlineCode: "",
    tanNo: "MYSA12345G",
    businessCategory: "Retail",
    country: "India",
    caf: "CAF006",
    compoundingScheme: "Yes",
    psuGovtOrganization: "No",
    remarks: "",
    active: false,
    bankName: "Canara Bank",
    branch: "Mysore",
    bankAddress: "Mysore",
    accountNo: "456123789000",
    accountTypeBank: "Savings",
    ifscCode: "CNRB0006789",
    swift: "CNRBINBB",
    contactPerson: "Ramesh",
    mobile: "9876501234",
    contactEmail: "ramesh@sla.com",
    city: "Mysore",
    state: "Karnataka",
    stateCode: "KA",
    stateNo: 29,
  },
];

    data.sort((a, b) => b.id - a.id);

    setPartyData(data);
    setLoading(false);
  };

  useEffect(() => {
    loadParties();
  }, []);

  const handleEdit = (party) => {
    onEdit(party);
  };

  const columns = [
  {
    key: "partyCode",
    label: "Party Code",
    accessor: "partyCode",
    type: "text",
    noWrap: true,
  },
  {
    key: "partyName",
    label: "Party Name",
    accessor: "partyName",
    type: "text",
  },
  {
    key: "shortName",
    label: "Short Name",
    accessor: "shortName",
    type: "text",
  },
  {
    key: "partyType",
    label: "Party Type",
    accessor: "partyType",
    type: "text",
  },
  {
    key: "customerType",
    label: "Customer Type",
    accessor: "customerType",
    type: "text",
  },
  {
    key: "businessType",
    label: "Business Type",
    accessor: "businessType",
    type: "text",
  },
  {
    key: "accountType",
    label: "Account Type",
    accessor: "accountType",
    type: "text",
  },
  {
    key: "gstRegistered",
    label: "GST Registered",
    accessor: "gstRegistered",
    type: "status",
    statusVariants: {
      true: {
        label: "Yes",
        className:
          "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300",
      },
      false: {
        label: "No",
        className:
          "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300",
      },
    },
  },
  {
    key: "gstNo",
    label: "GSTIN",
    accessor: "gstNo",
    type: "text",
    noWrap: true,
  },
  {
    key: "panNo",
    label: "PAN No",
    accessor: "panNo",
    type: "text",
  },
  {
    key: "mobile",
    label: "Mobile",
    accessor: "mobile",
    type: "text",
  },
  {
    key: "country",
    label: "Country",
    accessor: "country",
    type: "text",
  },
  {
    key: "currency",
    label: "Currency",
    accessor: "currency",
    type: "text",
  },
  {
    key: "salesPerson",
    label: "Sales Person",
    accessor: "salesPerson",
    type: "text",
  },
  {
    key: "creditLimit",
    label: "Credit Limit",
    accessor: "creditLimit",
    type: "text",
    align: "right",
  },
  {
    key: "creditDays",
    label: "Credit Days",
    accessor: "creditDays",
    type: "text",
    align: "center",
  },
  {
    key: "active",
    label: "Status",
    accessor: "active",
    type: "status",
    statusVariants: {
      true: {
        label: "Active",
        className:
          "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300",
      },
      false: {
        label: "Inactive",
        className:
          "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300",
      },
    },
  },
  {
    key: "actions",
    label: "Actions",
    type: "actions",
    align: "center",
    width: "90px",
  },
];

  const searchFields = [
  "partyCode",
  "partyName",
  "shortName",
  "partyType",
  "customerType",
  "businessType",
  "accountType",
  "gstNo",
  "panNo",
  "mobile",
  "country",
  "currency",
  "salesPerson",
];

  const filterOptions = [
    {
      value: "all",
      label: "All",
      field: null,
    },
    {
      value: "active",
      label: "Active",
      field: "active",
      filterValue: "active",
      activeValue: "Active",
    },
    {
      value: "inactive",
      label: "Inactive",
      field: "active",
      filterValue: "inactive",
      activeValue: "Active",
    },
  ];

  return (
    <CommonListViewTable
      title="Party "
      data={partyData}
      loading={loading}
      columns={columns}
      searchFields={searchFields}
      filterOptions={filterOptions}
      defaultFilter="all"
      onBack={onBack}
      onAddNew={onAddNew}
      onEdit={handleEdit}
      onView={false}
      showSerialNumber={true}
      itemsPerPageOptions={[5, 10, 20, 50, 100]}
      defaultItemsPerPage={10}
      emptyMessage="No Parties found"
      loadingMessage="Loading Parties..."
      enableRefresh={true}
      onRefresh={loadParties}
      enableExport={true}
      exportFileName="Parties"
    />
  );
};

export default PartyMasterList;